# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 446)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnThreshold = QtWidgets.QPushButton(self.centralwidget)
        self.btnThreshold.setEnabled(True)
        self.btnThreshold.setGeometry(QtCore.QRect(661, 310, 120, 30))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnThreshold.setFont(font)
        self.btnThreshold.setObjectName("btnThreshold")
        self.btnGray = QtWidgets.QPushButton(self.centralwidget)
        self.btnGray.setEnabled(True)
        self.btnGray.setGeometry(QtCore.QRect(501, 310, 120, 30))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnGray.setFont(font)
        self.btnGray.setObjectName("btnGray")
        self.btnReadImage = QtWidgets.QPushButton(self.centralwidget)
        self.btnReadImage.setEnabled(True)
        self.btnReadImage.setGeometry(QtCore.QRect(340, 310, 120, 30))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnReadImage.setFont(font)
        self.btnReadImage.setObjectName("btnReadImage")
        self.btnCapture = QtWidgets.QPushButton(self.centralwidget)
        self.btnCapture.setEnabled(True)
        self.btnCapture.setGeometry(QtCore.QRect(180, 310, 120, 30))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnCapture.setFont(font)
        self.btnCapture.setObjectName("btnCapture")
        self.btnOpenCamera = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenCamera.setEnabled(True)
        self.btnOpenCamera.setGeometry(QtCore.QRect(20, 310, 120, 30))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnOpenCamera.setFont(font)
        self.btnOpenCamera.setObjectName("btnOpenCamera")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 60, 150, 150))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 60, 150, 150))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(570, 60, 150, 150))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnOpenCamera.clicked.connect(MainWindow.btnOpenCamera_Clicked)
        self.btnCapture.clicked.connect(MainWindow.btnCapture_Clicked)
        self.btnReadImage.clicked.connect(MainWindow.btnReadImage_Clicked)
        self.btnGray.clicked.connect(MainWindow.btnGray_Clicked)
        self.btnThreshold.clicked.connect(MainWindow.btnThreshold_Clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnThreshold.setText(_translate("MainWindow", "阈值分割"))
        self.btnGray.setText(_translate("MainWindow", "灰度化"))
        self.btnReadImage.setText(_translate("MainWindow", "打开图片"))
        self.btnCapture.setText(_translate("MainWindow", "捕获图片"))
        self.btnOpenCamera.setText(_translate("MainWindow", "打开摄像头"))
        self.label.setText(_translate("MainWindow", "摄像头"))
        self.label_2.setText(_translate("MainWindow", "捕获图"))
        self.label_3.setText(_translate("MainWindow", "结果图"))

